apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    dolphindb.io/component.config: controller-config
  name: controller-config
data:
  {{ $controller_workerNum := ( include "controller.workerNum" . ) -}}
  {{ $controller_maxMemSize := ( include "controller.maxMemSize" . ) -}}
  {{ $agentPort := .Values.agent.port -}}
  {{ $serviceName := ( include "statefulset.name" . ) -}}
  {{ $controllerPort := .Values.controller.port -}}
  controller.cfg: |-
    localSite={{ $serviceName }}:{{ $.Values.controller.port }}:controller0
    webWorkerNum={{ $controller_workerNum }}
    workerNum={{ $controller_workerNum }}
    maxMemSize={{ $controller_maxMemSize }}
    dataSync=1
    lanCluster=0
    perfMonitoring=1
    dfsMetaDir=/data/ddb/server/log
    datanodeRestartInterval= {{- .Values.global.datanodeRestartInterval }}
  cluster.cfg: |-
    workerNum={{ $controller_workerNum }}
    maxMemSize={{ $controller_maxMemSize }}
    dataSync=1
    lanCluster=0
    chunkCacheEngineMemSize= {{- .Values.global.chunkCacheEngineMemSize }}
    volumeUsageThreshold=0.95
    {{- $values := .Values -}}
    {{ range $i := until (int .Values.global.agentNum) }}
    datanode{{ $i }}.volumes={{ include "cluster.config.volumes" (dict "NodeIndex" $i "Values" $values ) }}
    {{- end }}
    maxPartitionNumPerQuery={{- include "maxPartitionNumPerQuery" . }}
  cluster.nodes: |-
    localSite,mode
    {{ $serviceName }}:{{ .Values.controller.port }}:controller0,controller
    {{- $datanodePort := .Values.agent.datanodePort -}}
    {{ $serviceName }}:{{ $agentPort }}:agent0,agent
    {{ range $i := until (int .Values.global.agentNum) }}
    {{ $serviceName }}:{{ add $datanodePort ( mul $i 10 ) }}:datanode{{ $i }},datanode
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    dolphindb.io/component.config: agent-config
  name: agent-config
data:
  {{ $agentCpu := .Values.agent.resources.limits.cpu -}}
  {{ $agentMem := ( include "agent.maxMemSize" . ) -}}
  agent.cfg: |-
    mode=agent
    localSite={{ $serviceName }}:{{ $agentPort }}:agent0
    controllerSite={{ $serviceName }}:{{ $controllerPort }}:controller0
    maxMemSize={{ $agentMem }}
    webWorkerNum={{ $agentCpu }}
    workerNum={{ $agentCpu }}
    lanCluster=0
    perfMonitoring=1
    dfsMetaDir=/data/ddb/server/log
