apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    dolphindb.io/component.config: controller-config
  name: controller-config
data:
  {{ $controller_workerNum := ( include "controller.workerNum" . ) -}}
  {{ $controller_maxMemSize := .Values.controller.resources.limits.memory -}}
  {{ $agentPort := .Values.agent.port -}}
  {{ $serviceName := ( include "statefulset.name" . )}}
  {{ $controllerPort := .Values.controller.port -}}
  controller.cfg: |-
    localSite={{ $serviceName }}:{{ $.Values.controller.port }}:controller0
    webWorkerNum={{ $controller_workerNum }}
    workerNum={{ $controller_workerNum }}
    maxMemSize={{ $controller_maxMemSize }}
    dataSync=1
    lanCluster=0
    perfMonitoring=1
    dfsMetaDir=/data/ddb/server/log
    datanodeRestartInterval= {{- .Values.global.datanodeRestartInterval }}
  cluster.cfg: |-
    workerNum={{ $controller_workerNum }}
    maxMemSize={{ $controller_maxMemSize }}
    dataSync=1
    lanCluster=0
    chunkCacheEngineMemSize= {{- .Values.global.chunkCacheEngineMemSize }}
    volumeUsageThreshold=0.95
    volumes={{ include "cluster.config.volumes" . }}
  cluster.nodes: |-
    localSite,mode
    {{ $serviceName }}:{{ .Values.controller.port }}:controller0,controller
    {{- $datanodePort := .Values.agent.datanodePort -}}
    {{ range $i := until (int .Values.global.agentNum) }}
    {{ $serviceName }}:{{ add $agentPort ( mul $i 10 ) }}:agent{{ $i }},agent
    {{ $serviceName }}:{{ add $datanodePort ( mul $i 10 ) }}:datanode{{ $i }},datanode
    {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    dolphindb.io/component.config: agent-config
  name: agent-config
data:
  {{ $agentCpu := .Values.agent.resources.limits.cpu -}}
  {{ $agentMem := .Values.agent.resources.limits.memory -}}
  {{ range $i := until (int .Values.global.agentNum ) -}}
  agent{{ $i }}.cfg: |-
    mode=agent
    localSite={{ $serviceName }}:{{ add $agentPort ( mul $i 10 ) }}:agent{{ $i }}
    controllerSite={{ $serviceName }}:{{ $controllerPort }}:controller0
    maxMemSize={{ $agentMem }}
    webWorkerNum={{ $agentCpu }}
    workerNum={{ $agentCpu }}
    lanCluster=0
    perfMonitoring=1
    dfsMetaDir=/data/ddb/server/log
  {{ end }}