{{ $controll_storageClass := .Values.controller.storageClass | default .Values.global.storageClass -}}
{{ $agent_storageClass := .Values.agent.storageClass | default .Values.global.storageClass -}}
{{ $ns := .Release.Namespace -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-log
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $controll_storageClass }}
  resources:
    requests:
      storage: {{ .Values.controller.logSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-data
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $controll_storageClass }}
  resources:
    requests:
      storage: {{ .Values.controller.dataSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: controller-core
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $controll_storageClass }}
  resources:
    requests:
      storage: {{ .Values.controller.logSize }}
{{ $dataSize := .Values.agent.dataSize -}}
{{ $logSize := .Values.agent.logSize -}}
{{ $numOfVolume := .Values.agent.numberOfVolume -}}
{{ range $i := until (int .Values.global.agentNum) -}}
{{ range $j := until (int $numOfVolume) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-volume-{{ $i }}-{{ $j }}
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $agent_storageClass }}
  resources:
    requests:
      storage: {{ $dataSize }}
{{ end -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-data-{{ $i }}
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $agent_storageClass }}
  resources:
    requests:
      storage: {{ $logSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-log-{{ $i }}
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $agent_storageClass }}
  resources:
    requests:
      storage: {{ $logSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-core-{{ $i }}
  namespace: {{ $ns }}
  labels:
    dolphindb.io/component.type: Agent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $agent_storageClass }}
  resources:
    requests:
      storage: {{ $logSize }}
{{ end -}}