apiVersion: v1
kind: Service
metadata:
  name: {{ include "statefulset.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    dolphindb.io/component.type: controller
    dolphindb.io/dolphindb.version: {{ .Values.dolphindb.imageTags }}
spec:
  type: {{ include "controller.serviceType" . }}
  selector:
    dolphindb.io/component: dolphindb-singleton-cluster
  ports:
  - name: controller
    protocol: TCP
    port: 31210
  {{- $datanodePort := .Values.agent.datanodePort -}}
  {{- $agentPort := .Values.agent.port -}}
  {{ range $i := until (int .Values.global.agentNum) }}
  - name: datanode-{{ $i }}
    protocol: TCP
    port: {{ add $datanodePort ( mul $i 10 ) }}
  - name: agent-{{ $i }}
    protocol: TCP
    port: {{ add $agentPort ( mul $i 10 ) }}
  {{- end }}